# Generated by Django 2.1.4 on 2018-12-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('job_status', models.CharField(choices=[('1', 'Principal Investigator'), ('2', 'Post-doctoral Fellow'), ('3', 'Graduate Student'), ('4', 'Research Staff'), ('5', 'Lab Alumni'), ('6', 'Undergraduate Researcher'), ('7', 'Former Undergraduate Researcher')], default='3', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('current_job', models.CharField(blank=True, max_length=1000)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('cv', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1000)),
                ('journal', models.CharField(max_length=1000)),
                ('link', models.URLField(max_length=1000)),
            ],
        ),
    ]
