# Generated by Django 2.1.4 on 2018-12-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolleyMain', '0003_auto_20181224_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='labnewsitem',
            name='header',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
