# Generated by Django 2.1.4 on 2018-12-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolleyMain', '0004_labnewsitem_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labnewsitem',
            name='header',
            field=models.CharField(max_length=1000),
        ),
    ]
