# Generated by Django 2.1.4 on 2018-12-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolleyMain', '0005_auto_20181224_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='woolleyMain/default_profile_pic.jpg', upload_to=''),
        ),
    ]
